<?php

return [
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd. Urea',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '57',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MOH HATTA FARIH',
            'B' => null,
            'C' => null,
            'D' => null,
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd. Urea',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '58',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'RHESTA PRAYOGA U',
            'B' => 'AINUR ROFIK',
            'C' => 'BAMBANG SUGIANTO',
            'D' => 'HAPI',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd. Urea',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '59',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ABDUR ROHMAN',
            'B' => 'ACHMAD JAILANI',
            'C' => 'SAIFUL ARIF',
            'D' => 'M.AFTON ILMAN HUDA',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd. Urea',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '60',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SADELI',
            'B' => 'TOMI ANDRIYANTO',
            'C' => 'FATTAHUL AZIZ ZULFIKAR',
            'D' => 'RIDWAN EFENDI',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd ZA',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '61',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'NUR AHMAD MUBAROK',
            'B' => 'SUBANDI',
            'C' => 'AGENG EKO C',
            'D' => 'AHMAD SHOBARI',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd ZA',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '70',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUROSO',
            'B' => 'QHUSNUL QHULUQ',
            'C' => 'AHMAD MASRUCHIN',
            'D' => 'KIKI FIRMANSYAH',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd ZA',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '25-12',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ASMUNI',
            'B' => 'M. SAPUAN',
            'C' => 'ASHARI',
            'D' => 'MUKHTAR SYAFI I',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd ZA',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '25-13',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'AGUS HARIYANTO',
            'B' => 'ANIS DWI PRASETYO',
            'C' => 'ROKHIM',
            'D' => 'HAIKAL FERNANDO P',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'Gudang 1',
        'unit_kerja' => 'Gd ZA',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '25-14',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MULYONO TAUFIQ',
            'B' => 'MUH ZAKARIYA',
            'C' => 'AKH.MUDZAKIR',
            'D' => 'MOCH ULIN NUHA',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '75',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'IMAM AS\'ARI',
            'B' => 'HARI SUBAGIO',
            'C' => 'LADI',
            'D' => 'MUHAMMAD SAFI\'I',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '87',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ANANG PURNAWAN KUSUMA W',
            'B' => 'WAHYUDI',
            'C' => 'M SYAIFUDIN GHUFRON NAFI',
            'D' => 'AGUS SETYAWAN',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '88',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MAHFUDIN',
            'B' => 'MUKHAMAD CHAMZAH',
            'C' => 'SUKIN WANTO',
            'D' => 'TRI NOVI SETIONO',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '89',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ABDUL ROHIM',
            'B' => 'HERU SUKMONO',
            'C' => 'FACHRUL ANAM',
            'D' => 'DIAN SLAMET BUDIANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-90',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'KHOIRUL FATIHIN',
            'B' => 'ROHANTO',
            'C' => 'BENY DWI SAPUTRA',
            'D' => 'ABDUL WARAS',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-91',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MACHMUD',
            'B' => 'PUJI ISTIADI',
            'C' => 'MAGHFUR',
            'D' => 'MUHAMMAD FAUZI',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-92',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'RUSIDI',
            'B' => 'M. NAILUL AUTHOR',
            'C' => 'CHAMIM',
            'D' => 'SUKI HARIYANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang PF 1/ G.D 2',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-93',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MUHAMMAD ROBITH RICHABI',
            'B' => 'JAUHARIL MAKNUN',
            'C' => 'UMAR SAID',
            'D' => 'DEDI DWI ASTOMO',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Bahan pembantu',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '74',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'DAHLAN',
            'B' => 'TOMI WIDI UTOMO',
            'C' => 'SUDAR',
            'D' => 'ACH. MUSTAKIM',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-94',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ABDULLAH YAZID CHUSAIN',
            'B' => 'ROHMAD',
            'C' => 'MUHAMAD LAJIM',
            'D' => 'JAINUL ABIDIN',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-95',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SURYADI',
            'B' => 'NURUL ADRIYANTO',
            'C' => 'RUSLI',
            'D' => 'HONI',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-96',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SHOMAD',
            'B' => 'ABDUL MALIK',
            'C' => 'RADIONO',
            'D' => 'M. TAUFIK',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-97',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MUHAMMAD YUNUS',
            'B' => 'SUGIYO',
            'C' => 'HERRY SUSANTO',
            'D' => 'DHEDY R',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-98',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'NAWI',
            'B' => 'MUDLOFIR',
            'C' => 'HASIM',
            'D' => 'SYAFI\'I',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gudang 2',
        'unit_kerja' => 'Gudang Phonska 1',
        'kebutuhan_alat_inti' => 6,
        'no_lambung' => '25-99',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SAMUKID',
            'B' => 'MUSLIH',
            'C' => 'AHMAD USMAN SAPUTRA',
            'D' => 'SHODIK',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-01',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'A. ANDI ALFIANTO',
            'B' => 'AMIN GHOZALI',
            'C' => 'ABDUS SALAM',
            'D' => 'ACH. BAJURI',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-02',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'AHMAD ZAINUL ALAM',
            'B' => 'FAIZZULHAQ MA\'ARIF',
            'C' => 'AKHMAD SADILI',
            'D' => 'ARIS SUSANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-03',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ASIFUDDIN',
            'B' => 'HARIANTO',
            'C' => 'BAMBANG RUSANTO',
            'D' => 'KHUSNUL TAUFIQ',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-04',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'BALIYAH',
            'B' => 'IRHAM',
            'C' => 'MISBACHUL ACHYAR',
            'D' => 'LUKMAN KHAKIM',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-05',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUKAIMIN',
            'B' => 'MUHAMMAD MUJIONO',
            'C' => 'M. SYAUFIQ RIDWAN',
            'D' => 'MUKHAMMAD SLAMET',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-06',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MOCHAMAD SA\'RONI',
            'B' => 'MUHAMMAD SHUBEKHI',
            'C' => 'MOH. ARIES RINALDI',
            'D' => 'NUR HIDAYAT',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-07',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'YASMAN',
            'B' => 'SUNARDIONO',
            'C' => 'ROBBAH MA\'SUM',
            'D' => 'UBAIDILLAH',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Gudang 3',
        'unit_kerja' => 'Gudang PF II/ G.D 3',
        'kebutuhan_alat_inti' => 8,
        'no_lambung' => '25-08',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUKERMAN',
            'B' => 'SYAIFUL ANWAR',
            'C' => 'AGUS EFENDI',
            'D' => 'IMAM SAFI\'I',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK II, III, IV',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '53',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MUSLIKH',
            'B' => 'NUR HASIM',
            'C' => 'ALI AFANDI',
            'D' => 'SAIFUL WATHON',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK II, III, IV',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '79',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'HARIONO',
            'B' => 'MARWANTO',
            'C' => 'BAHRUL ULUM',
            'D' => 'INDRA SULISTIANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK II, III, IV',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '25-09',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MUHAMMAD AMIN',
            'B' => 'NURSAN',
            'C' => 'ANIB UBAIDILLAH',
            'D' => 'AGUS DWI HANDOKO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK II, III, IV',
        'kebutuhan_alat_inti' => 4,
        'no_lambung' => '25-10',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUKO PURWANTO',
            'B' => 'HARI',
            'C' => 'AHMAD JAYUS',
            'D' => 'MAHMUD ZAENURI',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK I & ZK I',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '50',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'RINTON DISTORI',
            'B' => null,
            'C' => null,
            'D' => null,
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'NPK I & ZK I',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '77',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ARIF MALIKI',
            'B' => 'SIRILIUS DWI ARI',
            'C' => 'MUKIM',
            'D' => 'SUGITO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Bahan Pembantu',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '78',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'NARTO',
            'B' => 'NURSAN',
            'C' => 'ANDRE SANDIJA PUTRA',
            'D' => 'ARIF MUZAKKY',
        ],
    ],
    [
        'zona' => 'ZONA 3',
        'area_kerja' => 'Gudang Pabrik III',
        'unit_kerja' => 'ALF3',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '65',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'DIDIN ASI P',
            'B' => 'SUWARNO',
            'C' => 'ROHMAD',
            'D' => 'M. NUR CHOLIS',
        ],
    ],
    [
        'zona' => 'ZONA 3',
        'area_kerja' => 'Gudang Pabrik III',
        'unit_kerja' => 'Gudang IV',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '64',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'NOR CHOLIS',
            'B' => 'NUR HUDA WIJAYA',
            'C' => 'EKO CAHYANTO',
            'D' => 'PUJIONO',
        ],
    ],
    [
        'zona' => 'ZONA 3',
        'area_kerja' => 'Gudang Pabrik III',
        'unit_kerja' => 'Revamping',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '63',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SAMSUL ARIF',
            'B' => 'ARIS',
            'C' => 'UGIK KRISTIAN',
            'D' => 'BAMBANG SUDIYANTO',
        ],
    ],
    [
        'zona' => 'ZONA 3',
        'area_kerja' => 'Gudang Pabrik III',
        'unit_kerja' => 'Gudang 38',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '25-11',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'HERY S',
            'B' => null,
            'C' => null,
            'D' => null,
        ],
    ],
    [
        'zona' => 'ZONA 3',
        'area_kerja' => 'Gudang Pabrik III',
        'unit_kerja' => 'Gudang 38',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '62',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MAT SUPI\'I',
            'B' => null,
            'C' => null,
            'D' => null,
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'AMUREA II',
        'unit_kerja' => 'Gudang Urea II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '71',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MARMO',
            'B' => 'PURNOMO',
            'C' => 'SUSANTO',
            'D' => 'SUROSO',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'AMUREA II',
        'unit_kerja' => 'Gudang Urea II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '72',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'YASIR',
            'B' => 'MIFTAKUL ROZAK',
            'C' => 'HUDA',
            'D' => 'MAS DARUL ILMI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'AMUREA II',
        'unit_kerja' => 'Gudang Urea II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '73',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'DEVANIARDIAS YUDHA',
            'B' => 'SUROSO',
            'C' => 'FAUZI ILMI',
            'D' => 'A YAZID',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'AMUREA II',
        'unit_kerja' => 'Gudang Urea II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '80',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ALI MUDYAKIR',
            'B' => 'HANIF KUSWANTO',
            'C' => 'GATOT',
            'D' => 'SUDARMANTO',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'AMUREA II',
        'unit_kerja' => 'Gudang Urea II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '81',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'NAFIK',
            'B' => 'M MAULIDHUN NS',
            'C' => 'YAHYA',
            'D' => 'YUDI RIZKI P',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG I',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '67',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUWARNO',
            'B' => 'M DAVID INDRA',
            'C' => 'ARDIANSYAH',
            'D' => 'Z BATUBARA',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG I',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '82',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'JEFFRI KURNIAWAN',
            'B' => 'M LUTFI',
            'C' => 'DJAINURI',
            'D' => 'M UMAMUDIN',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG I',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '83',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'SUWARNO',
            'B' => 'M DAVID INDRA',
            'C' => 'M TAHFIAN HAMID',
            'D' => 'MARSUDI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG I',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '84',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ANANG SULISTIONO',
            'B' => 'MAGHFIRUL GHONI',
            'C' => 'ARBAIN NAWAWI',
            'D' => 'ZULKIPLI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG I',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '85',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'TAUFIK SALEH',
            'B' => 'M JAMIL',
            'C' => 'NURUL YAQIN',
            'D' => 'RADIONO',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '25-15',
        'kepemilikan' => 'K3PG',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ACHMAD CHANIF S',
            'B' => 'SEPTIAN AGUS W',
            'C' => 'SUKUR',
            'D' => 'SLAMET WAHYUDI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '25-16',
        'kepemilikan' => 'K3PG',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'TAUFIK',
            'B' => 'M LUTFI',
            'C' => 'SUKUR',
            'D' => 'M. PRIDANI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '68',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'MOHAMMAD BASORI',
            'B' => 'YONGKI YOLANDA',
            'C' => 'ENDIK FRADANA',
            'D' => 'M UMAMUDIN',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '76',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'ACHMAD CHANIF S',
            'B' => 'FAHMI MUZAKI',
            'C' => 'DJAINURI',
            'D' => 'M PRIDANI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'GMG',
        'unit_kerja' => 'GMG II',
        'kebutuhan_alat_inti' => 5,
        'no_lambung' => '86',
        'kepemilikan' => 'YAYASAN',
        'jenis_alat' => 'Forklift',
        'operators' => [
            'A' => 'RUDI MULYADI',
            'B' => 'SEPTIAN AGUS W',
            'C' => 'ARDIANSYAH',
            'D' => 'Z BATUBARA',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Loading BB ZA Phn III O9-250 &',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '46',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ALI MASUD',
            'B' => 'AGUS J',
            'C' => 'MOCH USADANI',
            'D' => 'AMININ',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Loading BB ZA ROP 02-250',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '60',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'KHOIRON',
            'B' => 'M. ZAINUL',
            'C' => 'ANDINI WAHYU TIRTO',
            'D' => 'KHOIRUL',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Loading BB  Urea / KCL 2 & 3',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '49',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'SULAIMAN',
            'B' => 'M. IZZANUDIN',
            'C' => 'M. BUDI ROHMAN',
            'D' => 'AS\'ARI',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Loading BB phn I',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '25-71',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'SLAMET',
            'B' => 'IMAM QODIM',
            'C' => 'SUPA\'AT',
            'D' => 'YOHANES UTOMO',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Phonska 5/PF I',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '25-75',
        'kepemilikan' => 'BAA',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'BANDI ALI',
            'B' => 'AANK.K',
            'C' => 'ABD CHOLIK',
            'D' => 'MAKRUS ALI',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Muat Curah 09-400',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '67',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'MAURI',
            'B' => 'WINARTO',
            'C' => 'M. BURHANUDIN',
            'D' => 'ALI KHASAN',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Muat Curah 02-400',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '25-77',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'HARIYANTO',
            'B' => 'EDGAR N. T',
            'C' => 'ANDINI WAHYU TIRTO',
            'D' => 'M. SIHABUDIN',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Pabrik IIA',
        'unit_kerja' => 'Muat Curah 02-400',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '43',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'MOH. SYAIFUDIN',
            'B' => 'TIYAS',
            'C' => 'ABD CHOLIK',
            'D' => 'AGUS HARIYANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Loading BB phn IV',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '26-78',
        'kepemilikan' => 'BAA',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ADAM YUDI P',
            'B' => 'EKO KURNIAWAN S',
            'C' => 'AHMAD ROSIDIN',
            'D' => 'M.NAFI',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Loading BB phn IV',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '65',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'P. DAVID YULANDA',
            'B' => 'SUYONO',
            'C' => 'ABD.SALAM FANANI',
            'D' => 'ANGGA PRASTIAWAN',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Loading NPK II/III/IV',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '47',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ASHAR',
            'B' => 'AINUL YAQIN',
            'C' => 'RAHMAD TAUFIK ZEEN',
            'D' => 'MIFTAHUL HUDA',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Muat Curah 22-400',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '41',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'M. BASORI',
            'B' => 'AHMAD MUSYANTO',
            'C' => 'SETYO NOEGROHO',
            'D' => 'DEDY MISWIDYANTO',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Loading NPK I',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '25-74',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ISMAIL',
            'B' => 'TARMUJI',
            'C' => 'NURHADI',
            'D' => 'SAPUAN',
        ],
    ],
    [
        'zona' => 'ZONA 2B',
        'area_kerja' => 'Pabrik IIB',
        'unit_kerja' => 'Loading ZK I',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '45',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'M. EKO NUR JAELANI',
            'B' => 'ABDULLAH USMAN FARUQI',
            'C' => 'NURHADI',
            'D' => 'SAPUAN',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Asam Fosfat I & II',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '25-76',
        'kepemilikan' => 'BAA',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'MIRZA P',
            'B' => 'AS\'AD SAMSUL',
            'C' => 'ABD MUJIB',
            'D' => 'SAMSUL ANAM',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Asam Fosfat I & II',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '50',
        'kepemilikan' => 'BAA',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'FASHIKIN',
            'B' => 'KHUSNAN',
            'C' => 'M hamdan',
            'D' => 'MAAD HAZBULLOH E',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Asam Sulfat I & II',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '40',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ARIS D W',
            'B' => 'SHOLIHAN',
            'C' => 'Ach. yunan u',
            'D' => 'A. JUNAEDI',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Puri Gypsum I & II',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '25-72',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'MISBACHUL MUNIR',
            'B' => 'ROFIK',
            'C' => 'MASHUDI',
            'D' => 'A. RIFA\'I',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Puri Gypsum I & II',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '56',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'ADI GUNAWAN',
            'B' => 'JODI',
            'C' => 'MEI AGUNG',
            'D' => 'PUJIONO',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Pabrik III A/B',
        'unit_kerja' => 'Loading Gudang CR',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '25-73',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'JAINUL H',
            'B' => 'CHOIRI',
            'C' => 'MUTHAROSIDI',
            'D' => 'JAMIN',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'ZA II',
        'unit_kerja' => 'Loading Urea',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '68',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'YAHYA',
            'B' => 'M. SAMSUL ARIFIN',
            'C' => 'SHABIKIN',
            'D' => 'DENNY CAHYO',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'ZA II',
        'unit_kerja' => 'Loading ZA/BS Belerang',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '55',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'M. Abdul Ghoniy',
            'B' => 'AHMAD MURZAKI',
            'C' => 'KHOLIQIN',
            'D' => 'MUH ABDUL MAJID',
        ],
    ],
    [
        'zona' => 'ZONA 1A',
        'area_kerja' => 'ZA II',
        'unit_kerja' => 'Loading Gypsum',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '63',
        'kepemilikan' => 'WKK',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'KHOZIM',
            'B' => 'M. ISROQI',
            'C' => 'WARTONO',
            'D' => 'DANANG WAHYUDI',
        ],
    ],
    [
        'zona' => 'ZONA 1B',
        'area_kerja' => 'Amurea IB',
        'unit_kerja' => 'Loading Curah',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '64',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'GILANG',
            'B' => 'SUROSO',
            'C' => 'KHAFID',
            'D' => 'M. SHOLEH',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Gd. Urea 20.000',
        'unit_kerja' => 'Ekspor Curah',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '59',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'SUUDI',
            'B' => 'IHMALUL HUSAUNi',
            'C' => 'HANAFI',
            'D' => 'A. MUKLIS',
        ],
    ],
    [
        'zona' => 'ZONA 3 A/B',
        'area_kerja' => 'Gd. Urea 20.000',
        'unit_kerja' => 'Ekspor Curah',
        'kebutuhan_alat_inti' => 2,
        'no_lambung' => '54',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'AGUS DWI Y',
            'B' => 'SYAIFUL PRIO',
            'C' => 'BAHRUL ANAM',
            'D' => 'ABD. ASHAR MUKHLIS',
        ],
    ],
    [
        'zona' => 'ZONA 2A',
        'area_kerja' => 'Gd. 25.000',
        'unit_kerja' => 'KCL BB',
        'kebutuhan_alat_inti' => 1,
        'no_lambung' => '62',
        'kepemilikan' => 'PCS',
        'jenis_alat' => 'Wheel Loader',
        'operators' => [
            'A' => 'GURUH',
            'B' => 'RIFAI',
            'C' => 'M NIDHOM',
            'D' => 'MIJO',
        ],
    ],
];
