-- =====================================================================
-- CUCI ALBER - DATABASE SCHEMA + SEED DATA
-- Import file ini langsung ke MySQL (phpMyAdmin / mysql CLI) untuk
-- membuat semua tabel + data awal, TANPA perlu `php artisan migrate`.
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------
-- Tabel bawaan Laravel
-- ---------------------------------------------------------------------

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL DEFAULT 'admin',
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id` varchar(255) NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `payload` longtext NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cache`;
CREATE TABLE `cache` (
  `key` varchar(255) NOT NULL,
  `value` mediumtext NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE `cache_locks` (
  `key` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) NOT NULL,
  `payload` longtext NOT NULL,
  `attempts` tinyint unsigned NOT NULL,
  `reserved_at` int unsigned DEFAULT NULL,
  `available_at` int unsigned NOT NULL,
  `created_at` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `job_batches`;
CREATE TABLE `job_batches` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `total_jobs` int NOT NULL,
  `pending_jobs` int NOT NULL,
  `failed_jobs` int NOT NULL,
  `failed_job_ids` longtext NOT NULL,
  `options` mediumtext,
  `cancelled_at` int DEFAULT NULL,
  `created_at` int NOT NULL,
  `finished_at` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Tabel aplikasi Cuci Alber
-- ---------------------------------------------------------------------

DROP TABLE IF EXISTS `zonas`;
CREATE TABLE `zonas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `zonas_nama_unique` (`nama`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `area_kerjas`;
CREATE TABLE `area_kerjas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `zona_id` bigint unsigned NOT NULL,
  `nama` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `area_kerjas_zona_id_nama_unique` (`zona_id`,`nama`),
  CONSTRAINT `area_kerjas_zona_id_foreign` FOREIGN KEY (`zona_id`) REFERENCES `zonas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `unit_kerjas`;
CREATE TABLE `unit_kerjas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `area_kerja_id` bigint unsigned NOT NULL,
  `nama` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unit_kerjas_area_kerja_id_nama_unique` (`area_kerja_id`,`nama`),
  CONSTRAINT `unit_kerjas_area_kerja_id_foreign` FOREIGN KEY (`area_kerja_id`) REFERENCES `area_kerjas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `jenis_alats`;
CREATE TABLE `jenis_alats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `jenis_alats_nama_unique` (`nama`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `operators`;
CREATE TABLE `operators` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `no_hp` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `unit_alats`;
CREATE TABLE `unit_alats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `unit_kerja_id` bigint unsigned NOT NULL,
  `jenis_alat_id` bigint unsigned NOT NULL,
  `no_lambung` varchar(255) NOT NULL,
  `kepemilikan` varchar(255) DEFAULT NULL,
  `keterangan` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `unit_alats_unit_kerja_id_jenis_alat_id_index` (`unit_kerja_id`,`jenis_alat_id`),
  CONSTRAINT `unit_alats_unit_kerja_id_foreign` FOREIGN KEY (`unit_kerja_id`) REFERENCES `unit_kerjas` (`id`) ON DELETE CASCADE,
  CONSTRAINT `unit_alats_jenis_alat_id_foreign` FOREIGN KEY (`jenis_alat_id`) REFERENCES `jenis_alats` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `unit_operators`;
CREATE TABLE `unit_operators` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `unit_alat_id` bigint unsigned NOT NULL,
  `operator_id` bigint unsigned NOT NULL,
  `grup` enum('A','B','C','D') NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unit_operators_unit_alat_id_grup_unique` (`unit_alat_id`,`grup`),
  KEY `unit_operators_operator_id_foreign` (`operator_id`),
  CONSTRAINT `unit_operators_unit_alat_id_foreign` FOREIGN KEY (`unit_alat_id`) REFERENCES `unit_alats` (`id`) ON DELETE CASCADE,
  CONSTRAINT `unit_operators_operator_id_foreign` FOREIGN KEY (`operator_id`) REFERENCES `operators` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `pengawas`;
CREATE TABLE `pengawas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `wilayah` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `submissions`;
CREATE TABLE `submissions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `unit_alat_id` bigint unsigned NOT NULL,
  `pengawas_id` bigint unsigned DEFAULT NULL,
  `shift` enum('1','2','3') NOT NULL,
  `operator_nd_id` bigint unsigned DEFAULT NULL,
  `operator_grup_a_id` bigint unsigned DEFAULT NULL,
  `operator_grup_b_id` bigint unsigned DEFAULT NULL,
  `operator_grup_c_id` bigint unsigned DEFAULT NULL,
  `operator_grup_d_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `zona_snapshot` varchar(255) DEFAULT NULL,
  `area_kerja_snapshot` varchar(255) DEFAULT NULL,
  `unit_kerja_snapshot` varchar(255) DEFAULT NULL,
  `jenis_alat_snapshot` varchar(255) DEFAULT NULL,
  `no_lambung_snapshot` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `submissions_unit_alat_id_foreign` (`unit_alat_id`),
  KEY `submissions_pengawas_id_foreign` (`pengawas_id`),
  KEY `submissions_operator_nd_id_foreign` (`operator_nd_id`),
  KEY `submissions_operator_grup_a_id_foreign` (`operator_grup_a_id`),
  KEY `submissions_operator_grup_b_id_foreign` (`operator_grup_b_id`),
  KEY `submissions_operator_grup_c_id_foreign` (`operator_grup_c_id`),
  KEY `submissions_operator_grup_d_id_foreign` (`operator_grup_d_id`),
  CONSTRAINT `submissions_unit_alat_id_foreign` FOREIGN KEY (`unit_alat_id`) REFERENCES `unit_alats` (`id`) ON DELETE CASCADE,
  CONSTRAINT `submissions_pengawas_id_foreign` FOREIGN KEY (`pengawas_id`) REFERENCES `pengawas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `submissions_operator_nd_id_foreign` FOREIGN KEY (`operator_nd_id`) REFERENCES `operators` (`id`) ON DELETE SET NULL,
  CONSTRAINT `submissions_operator_grup_a_id_foreign` FOREIGN KEY (`operator_grup_a_id`) REFERENCES `operators` (`id`) ON DELETE SET NULL,
  CONSTRAINT `submissions_operator_grup_b_id_foreign` FOREIGN KEY (`operator_grup_b_id`) REFERENCES `operators` (`id`) ON DELETE SET NULL,
  CONSTRAINT `submissions_operator_grup_c_id_foreign` FOREIGN KEY (`operator_grup_c_id`) REFERENCES `operators` (`id`) ON DELETE SET NULL,
  CONSTRAINT `submissions_operator_grup_d_id_foreign` FOREIGN KEY (`operator_grup_d_id`) REFERENCES `operators` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `submission_photos`;
CREATE TABLE `submission_photos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `submission_id` bigint unsigned NOT NULL,
  `path` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `submission_photos_submission_id_foreign` (`submission_id`),
  CONSTRAINT `submission_photos_submission_id_foreign` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Tandai semua migration Laravel sebagai sudah dijalankan
-- (supaya `php artisan migrate` di kemudian hari tidak bentrok)
-- ---------------------------------------------------------------------
INSERT INTO `migrations` (`migration`, `batch`) VALUES
('0001_01_01_000000_create_users_table', 1),
('0001_01_01_000001_create_cache_table', 1),
('0001_01_01_000002_create_jobs_table', 1),
('2025_01_01_000001_create_zonas_table', 1),
('2025_01_01_000002_create_area_kerjas_table', 1),
('2025_01_01_000003_create_unit_kerjas_table', 1),
('2025_01_01_000004_create_jenis_alats_table', 1),
('2025_01_01_000005_create_operators_table', 1),
('2025_01_01_000006_create_unit_alats_table', 1),
('2025_01_01_000007_create_unit_operators_table', 1),
('2025_01_01_000008_create_pengawas_table', 1),
('2025_01_01_000009_create_submissions_table', 1),
('2025_01_01_000010_add_role_to_users_table', 1),
('2025_01_02_000001_drop_kebutuhan_alat_inti_from_unit_kerjas_table', 1),
('2025_01_02_000002_create_submission_photos_table', 1);

-- ---------------------------------------------------------------------
-- Akun admin default (email: admin@cucialber.local / password: admin123)
-- SEGERA GANTI PASSWORD INI setelah login pertama kali!
-- ---------------------------------------------------------------------
INSERT INTO `users` (`name`, `email`, `role`, `password`, `created_at`, `updated_at`) VALUES
('Administrator', 'admin@cucialber.local', 'admin', '$2y$10$MOvQ8M0tRsbhQpX1FPuJketoYLSmbW4YXwhxBlIjBsRpadjDzwrMe', NOW(), NOW());

-- ---------------------------------------------------------------------
-- Data master: Zona, Area Kerja, Unit Kerja, Jenis Alat, Operator,
-- Unit Alat, Operator per Grup (A-D) - diambil dari Excel ploting asli
-- ---------------------------------------------------------------------
INSERT INTO `zonas` (`id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 'ZONA 1A', NOW(), NOW()),
(2, 'ZONA 2A', NOW(), NOW()),
(3, 'ZONA 2B', NOW(), NOW()),
(4, 'ZONA 3', NOW(), NOW()),
(5, 'ZONA 1B', NOW(), NOW()),
(6, 'ZONA 3 A/B', NOW(), NOW());

INSERT INTO `area_kerjas` (`id`, `zona_id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 1, 'Gudang 1', NOW(), NOW()),
(2, 2, 'Gudang 2', NOW(), NOW()),
(3, 3, 'Gudang 3', NOW(), NOW()),
(4, 3, 'Pabrik IIB', NOW(), NOW()),
(5, 4, 'Gudang Pabrik III', NOW(), NOW()),
(6, 5, 'AMUREA II', NOW(), NOW()),
(7, 5, 'GMG', NOW(), NOW()),
(8, 2, 'Pabrik IIA', NOW(), NOW()),
(9, 6, 'Pabrik III A/B', NOW(), NOW()),
(10, 1, 'ZA II', NOW(), NOW()),
(11, 5, 'Amurea IB', NOW(), NOW()),
(12, 6, 'Gd. Urea 20.000', NOW(), NOW()),
(13, 2, 'Gd. 25.000', NOW(), NOW());

INSERT INTO `unit_kerjas` (`id`, `area_kerja_id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 1, 'Gd. Urea', NOW(), NOW()),
(2, 1, 'Gd ZA', NOW(), NOW()),
(3, 2, 'Gudang PF 1/ G.D 2', NOW(), NOW()),
(4, 2, 'Bahan pembantu', NOW(), NOW()),
(5, 2, 'Gudang Phonska 1', NOW(), NOW()),
(6, 3, 'Gudang PF II/ G.D 3', NOW(), NOW()),
(7, 4, 'NPK II, III, IV', NOW(), NOW()),
(8, 4, 'NPK I & ZK I', NOW(), NOW()),
(9, 4, 'Bahan Pembantu', NOW(), NOW()),
(10, 5, 'ALF3', NOW(), NOW()),
(11, 5, 'Gudang IV', NOW(), NOW()),
(12, 5, 'Revamping', NOW(), NOW()),
(13, 5, 'Gudang 38', NOW(), NOW()),
(14, 6, 'Gudang Urea II', NOW(), NOW()),
(15, 7, 'GMG I', NOW(), NOW()),
(16, 7, 'GMG II', NOW(), NOW()),
(17, 8, 'Loading BB ZA Phn III O9-250 &', NOW(), NOW()),
(18, 8, 'Loading BB ZA ROP 02-250', NOW(), NOW()),
(19, 8, 'Loading BB  Urea / KCL 2 & 3', NOW(), NOW()),
(20, 8, 'Loading BB phn I', NOW(), NOW()),
(21, 8, 'Phonska 5/PF I', NOW(), NOW()),
(22, 8, 'Muat Curah 09-400', NOW(), NOW()),
(23, 8, 'Muat Curah 02-400', NOW(), NOW()),
(24, 4, 'Loading BB phn IV', NOW(), NOW()),
(25, 4, 'Loading NPK II/III/IV', NOW(), NOW()),
(26, 4, 'Muat Curah 22-400', NOW(), NOW()),
(27, 4, 'Loading NPK I', NOW(), NOW()),
(28, 4, 'Loading ZK I', NOW(), NOW()),
(29, 9, 'Loading Asam Fosfat I & II', NOW(), NOW()),
(30, 9, 'Loading Asam Sulfat I & II', NOW(), NOW()),
(31, 9, 'Loading Puri Gypsum I & II', NOW(), NOW()),
(32, 9, 'Loading Gudang CR', NOW(), NOW()),
(33, 10, 'Loading Urea', NOW(), NOW()),
(34, 10, 'Loading ZA/BS Belerang', NOW(), NOW()),
(35, 10, 'Loading Gypsum', NOW(), NOW()),
(36, 11, 'Loading Curah', NOW(), NOW()),
(37, 12, 'Ekspor Curah', NOW(), NOW()),
(38, 13, 'KCL BB', NOW(), NOW());

INSERT INTO `jenis_alats` (`id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 'Forklift', NOW(), NOW()),
(2, 'Wheel Loader', NOW(), NOW());

INSERT INTO `operators` (`id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 'MOH HATTA FARIH', NOW(), NOW()),
(2, 'RHESTA PRAYOGA U', NOW(), NOW()),
(3, 'AINUR ROFIK', NOW(), NOW()),
(4, 'BAMBANG SUGIANTO', NOW(), NOW()),
(5, 'HAPI', NOW(), NOW()),
(6, 'ABDUR ROHMAN', NOW(), NOW()),
(7, 'ACHMAD JAILANI', NOW(), NOW()),
(8, 'SAIFUL ARIF', NOW(), NOW()),
(9, 'M.AFTON ILMAN HUDA', NOW(), NOW()),
(10, 'SADELI', NOW(), NOW()),
(11, 'TOMI ANDRIYANTO', NOW(), NOW()),
(12, 'FATTAHUL AZIZ ZULFIKAR', NOW(), NOW()),
(13, 'RIDWAN EFENDI', NOW(), NOW()),
(14, 'NUR AHMAD MUBAROK', NOW(), NOW()),
(15, 'SUBANDI', NOW(), NOW()),
(16, 'AGENG EKO C', NOW(), NOW()),
(17, 'AHMAD SHOBARI', NOW(), NOW()),
(18, 'SUROSO', NOW(), NOW()),
(19, 'QHUSNUL QHULUQ', NOW(), NOW()),
(20, 'AHMAD MASRUCHIN', NOW(), NOW()),
(21, 'KIKI FIRMANSYAH', NOW(), NOW()),
(22, 'ASMUNI', NOW(), NOW()),
(23, 'M. SAPUAN', NOW(), NOW()),
(24, 'ASHARI', NOW(), NOW()),
(25, 'MUKHTAR SYAFI I', NOW(), NOW()),
(26, 'AGUS HARIYANTO', NOW(), NOW()),
(27, 'ANIS DWI PRASETYO', NOW(), NOW()),
(28, 'ROKHIM', NOW(), NOW()),
(29, 'HAIKAL FERNANDO P', NOW(), NOW()),
(30, 'MULYONO TAUFIQ', NOW(), NOW()),
(31, 'MUH ZAKARIYA', NOW(), NOW()),
(32, 'AKH.MUDZAKIR', NOW(), NOW()),
(33, 'MOCH ULIN NUHA', NOW(), NOW()),
(34, 'IMAM AS''ARI', NOW(), NOW()),
(35, 'HARI SUBAGIO', NOW(), NOW()),
(36, 'LADI', NOW(), NOW()),
(37, 'MUHAMMAD SAFI''I', NOW(), NOW()),
(38, 'ANANG PURNAWAN KUSUMA W', NOW(), NOW()),
(39, 'WAHYUDI', NOW(), NOW()),
(40, 'M SYAIFUDIN GHUFRON NAFI', NOW(), NOW()),
(41, 'AGUS SETYAWAN', NOW(), NOW()),
(42, 'MAHFUDIN', NOW(), NOW()),
(43, 'MUKHAMAD CHAMZAH', NOW(), NOW()),
(44, 'SUKIN WANTO', NOW(), NOW()),
(45, 'TRI NOVI SETIONO', NOW(), NOW()),
(46, 'ABDUL ROHIM', NOW(), NOW()),
(47, 'HERU SUKMONO', NOW(), NOW()),
(48, 'FACHRUL ANAM', NOW(), NOW()),
(49, 'DIAN SLAMET BUDIANTO', NOW(), NOW()),
(50, 'KHOIRUL FATIHIN', NOW(), NOW()),
(51, 'ROHANTO', NOW(), NOW()),
(52, 'BENY DWI SAPUTRA', NOW(), NOW()),
(53, 'ABDUL WARAS', NOW(), NOW()),
(54, 'MACHMUD', NOW(), NOW()),
(55, 'PUJI ISTIADI', NOW(), NOW()),
(56, 'MAGHFUR', NOW(), NOW()),
(57, 'MUHAMMAD FAUZI', NOW(), NOW()),
(58, 'RUSIDI', NOW(), NOW()),
(59, 'M. NAILUL AUTHOR', NOW(), NOW()),
(60, 'CHAMIM', NOW(), NOW()),
(61, 'SUKI HARIYANTO', NOW(), NOW()),
(62, 'MUHAMMAD ROBITH RICHABI', NOW(), NOW()),
(63, 'JAUHARIL MAKNUN', NOW(), NOW()),
(64, 'UMAR SAID', NOW(), NOW()),
(65, 'DEDI DWI ASTOMO', NOW(), NOW()),
(66, 'DAHLAN', NOW(), NOW()),
(67, 'TOMI WIDI UTOMO', NOW(), NOW()),
(68, 'SUDAR', NOW(), NOW()),
(69, 'ACH. MUSTAKIM', NOW(), NOW()),
(70, 'ABDULLAH YAZID CHUSAIN', NOW(), NOW()),
(71, 'ROHMAD', NOW(), NOW()),
(72, 'MUHAMAD LAJIM', NOW(), NOW()),
(73, 'JAINUL ABIDIN', NOW(), NOW()),
(74, 'SURYADI', NOW(), NOW()),
(75, 'NURUL ADRIYANTO', NOW(), NOW()),
(76, 'RUSLI', NOW(), NOW()),
(77, 'HONI', NOW(), NOW()),
(78, 'SHOMAD', NOW(), NOW()),
(79, 'ABDUL MALIK', NOW(), NOW()),
(80, 'RADIONO', NOW(), NOW()),
(81, 'M. TAUFIK', NOW(), NOW()),
(82, 'MUHAMMAD YUNUS', NOW(), NOW()),
(83, 'SUGIYO', NOW(), NOW()),
(84, 'HERRY SUSANTO', NOW(), NOW()),
(85, 'DHEDY R', NOW(), NOW()),
(86, 'NAWI', NOW(), NOW()),
(87, 'MUDLOFIR', NOW(), NOW()),
(88, 'HASIM', NOW(), NOW()),
(89, 'SYAFI''I', NOW(), NOW()),
(90, 'SAMUKID', NOW(), NOW()),
(91, 'MUSLIH', NOW(), NOW()),
(92, 'AHMAD USMAN SAPUTRA', NOW(), NOW()),
(93, 'SHODIK', NOW(), NOW()),
(94, 'A. ANDI ALFIANTO', NOW(), NOW()),
(95, 'AMIN GHOZALI', NOW(), NOW()),
(96, 'ABDUS SALAM', NOW(), NOW()),
(97, 'ACH. BAJURI', NOW(), NOW()),
(98, 'AHMAD ZAINUL ALAM', NOW(), NOW()),
(99, 'FAIZZULHAQ MA''ARIF', NOW(), NOW()),
(100, 'AKHMAD SADILI', NOW(), NOW()),
(101, 'ARIS SUSANTO', NOW(), NOW()),
(102, 'ASIFUDDIN', NOW(), NOW()),
(103, 'HARIANTO', NOW(), NOW()),
(104, 'BAMBANG RUSANTO', NOW(), NOW()),
(105, 'KHUSNUL TAUFIQ', NOW(), NOW()),
(106, 'BALIYAH', NOW(), NOW()),
(107, 'IRHAM', NOW(), NOW()),
(108, 'MISBACHUL ACHYAR', NOW(), NOW()),
(109, 'LUKMAN KHAKIM', NOW(), NOW()),
(110, 'SUKAIMIN', NOW(), NOW()),
(111, 'MUHAMMAD MUJIONO', NOW(), NOW()),
(112, 'M. SYAUFIQ RIDWAN', NOW(), NOW()),
(113, 'MUKHAMMAD SLAMET', NOW(), NOW()),
(114, 'MOCHAMAD SA''RONI', NOW(), NOW()),
(115, 'MUHAMMAD SHUBEKHI', NOW(), NOW()),
(116, 'MOH. ARIES RINALDI', NOW(), NOW()),
(117, 'NUR HIDAYAT', NOW(), NOW()),
(118, 'YASMAN', NOW(), NOW()),
(119, 'SUNARDIONO', NOW(), NOW()),
(120, 'ROBBAH MA''SUM', NOW(), NOW()),
(121, 'UBAIDILLAH', NOW(), NOW()),
(122, 'SUKERMAN', NOW(), NOW()),
(123, 'SYAIFUL ANWAR', NOW(), NOW()),
(124, 'AGUS EFENDI', NOW(), NOW()),
(125, 'IMAM SAFI''I', NOW(), NOW()),
(126, 'MUSLIKH', NOW(), NOW()),
(127, 'NUR HASIM', NOW(), NOW()),
(128, 'ALI AFANDI', NOW(), NOW()),
(129, 'SAIFUL WATHON', NOW(), NOW()),
(130, 'HARIONO', NOW(), NOW()),
(131, 'MARWANTO', NOW(), NOW()),
(132, 'BAHRUL ULUM', NOW(), NOW()),
(133, 'INDRA SULISTIANTO', NOW(), NOW()),
(134, 'MUHAMMAD AMIN', NOW(), NOW()),
(135, 'NURSAN', NOW(), NOW()),
(136, 'ANIB UBAIDILLAH', NOW(), NOW()),
(137, 'AGUS DWI HANDOKO', NOW(), NOW()),
(138, 'SUKO PURWANTO', NOW(), NOW()),
(139, 'HARI', NOW(), NOW()),
(140, 'AHMAD JAYUS', NOW(), NOW()),
(141, 'MAHMUD ZAENURI', NOW(), NOW()),
(142, 'RINTON DISTORI', NOW(), NOW()),
(143, 'ARIF MALIKI', NOW(), NOW()),
(144, 'SIRILIUS DWI ARI', NOW(), NOW()),
(145, 'MUKIM', NOW(), NOW()),
(146, 'SUGITO', NOW(), NOW()),
(147, 'NARTO', NOW(), NOW()),
(148, 'ANDRE SANDIJA PUTRA', NOW(), NOW()),
(149, 'ARIF MUZAKKY', NOW(), NOW()),
(150, 'DIDIN ASI P', NOW(), NOW()),
(151, 'SUWARNO', NOW(), NOW()),
(152, 'M. NUR CHOLIS', NOW(), NOW()),
(153, 'NOR CHOLIS', NOW(), NOW()),
(154, 'NUR HUDA WIJAYA', NOW(), NOW()),
(155, 'EKO CAHYANTO', NOW(), NOW()),
(156, 'PUJIONO', NOW(), NOW()),
(157, 'SAMSUL ARIF', NOW(), NOW()),
(158, 'ARIS', NOW(), NOW()),
(159, 'UGIK KRISTIAN', NOW(), NOW()),
(160, 'BAMBANG SUDIYANTO', NOW(), NOW()),
(161, 'HERY S', NOW(), NOW()),
(162, 'MAT SUPI''I', NOW(), NOW()),
(163, 'MARMO', NOW(), NOW()),
(164, 'PURNOMO', NOW(), NOW()),
(165, 'SUSANTO', NOW(), NOW()),
(166, 'YASIR', NOW(), NOW()),
(167, 'MIFTAKUL ROZAK', NOW(), NOW()),
(168, 'HUDA', NOW(), NOW()),
(169, 'MAS DARUL ILMI', NOW(), NOW()),
(170, 'DEVANIARDIAS YUDHA', NOW(), NOW()),
(171, 'FAUZI ILMI', NOW(), NOW()),
(172, 'A YAZID', NOW(), NOW()),
(173, 'ALI MUDYAKIR', NOW(), NOW()),
(174, 'HANIF KUSWANTO', NOW(), NOW()),
(175, 'GATOT', NOW(), NOW()),
(176, 'SUDARMANTO', NOW(), NOW()),
(177, 'NAFIK', NOW(), NOW()),
(178, 'M MAULIDHUN NS', NOW(), NOW()),
(179, 'YAHYA', NOW(), NOW()),
(180, 'YUDI RIZKI P', NOW(), NOW()),
(181, 'M DAVID INDRA', NOW(), NOW()),
(182, 'ARDIANSYAH', NOW(), NOW()),
(183, 'Z BATUBARA', NOW(), NOW()),
(184, 'JEFFRI KURNIAWAN', NOW(), NOW()),
(185, 'M LUTFI', NOW(), NOW()),
(186, 'DJAINURI', NOW(), NOW()),
(187, 'M UMAMUDIN', NOW(), NOW()),
(188, 'M TAHFIAN HAMID', NOW(), NOW()),
(189, 'MARSUDI', NOW(), NOW()),
(190, 'ANANG SULISTIONO', NOW(), NOW()),
(191, 'MAGHFIRUL GHONI', NOW(), NOW()),
(192, 'ARBAIN NAWAWI', NOW(), NOW()),
(193, 'ZULKIPLI', NOW(), NOW()),
(194, 'TAUFIK SALEH', NOW(), NOW()),
(195, 'M JAMIL', NOW(), NOW()),
(196, 'NURUL YAQIN', NOW(), NOW()),
(197, 'ACHMAD CHANIF S', NOW(), NOW()),
(198, 'SEPTIAN AGUS W', NOW(), NOW()),
(199, 'SUKUR', NOW(), NOW()),
(200, 'SLAMET WAHYUDI', NOW(), NOW());

INSERT INTO `operators` (`id`, `nama`, `created_at`, `updated_at`) VALUES
(201, 'TAUFIK', NOW(), NOW()),
(202, 'M. PRIDANI', NOW(), NOW()),
(203, 'MOHAMMAD BASORI', NOW(), NOW()),
(204, 'YONGKI YOLANDA', NOW(), NOW()),
(205, 'ENDIK FRADANA', NOW(), NOW()),
(206, 'FAHMI MUZAKI', NOW(), NOW()),
(207, 'M PRIDANI', NOW(), NOW()),
(208, 'RUDI MULYADI', NOW(), NOW()),
(209, 'ALI MASUD', NOW(), NOW()),
(210, 'AGUS J', NOW(), NOW()),
(211, 'MOCH USADANI', NOW(), NOW()),
(212, 'AMININ', NOW(), NOW()),
(213, 'KHOIRON', NOW(), NOW()),
(214, 'M. ZAINUL', NOW(), NOW()),
(215, 'ANDINI WAHYU TIRTO', NOW(), NOW()),
(216, 'KHOIRUL', NOW(), NOW()),
(217, 'SULAIMAN', NOW(), NOW()),
(218, 'M. IZZANUDIN', NOW(), NOW()),
(219, 'M. BUDI ROHMAN', NOW(), NOW()),
(220, 'AS''ARI', NOW(), NOW()),
(221, 'SLAMET', NOW(), NOW()),
(222, 'IMAM QODIM', NOW(), NOW()),
(223, 'SUPA''AT', NOW(), NOW()),
(224, 'YOHANES UTOMO', NOW(), NOW()),
(225, 'BANDI ALI', NOW(), NOW()),
(226, 'AANK.K', NOW(), NOW()),
(227, 'ABD CHOLIK', NOW(), NOW()),
(228, 'MAKRUS ALI', NOW(), NOW()),
(229, 'MAURI', NOW(), NOW()),
(230, 'WINARTO', NOW(), NOW()),
(231, 'M. BURHANUDIN', NOW(), NOW()),
(232, 'ALI KHASAN', NOW(), NOW()),
(233, 'HARIYANTO', NOW(), NOW()),
(234, 'EDGAR N. T', NOW(), NOW()),
(235, 'M. SIHABUDIN', NOW(), NOW()),
(236, 'MOH. SYAIFUDIN', NOW(), NOW()),
(237, 'TIYAS', NOW(), NOW()),
(238, 'ADAM YUDI P', NOW(), NOW()),
(239, 'EKO KURNIAWAN S', NOW(), NOW()),
(240, 'AHMAD ROSIDIN', NOW(), NOW()),
(241, 'M.NAFI', NOW(), NOW()),
(242, 'P. DAVID YULANDA', NOW(), NOW()),
(243, 'SUYONO', NOW(), NOW()),
(244, 'ABD.SALAM FANANI', NOW(), NOW()),
(245, 'ANGGA PRASTIAWAN', NOW(), NOW()),
(246, 'ASHAR', NOW(), NOW()),
(247, 'AINUL YAQIN', NOW(), NOW()),
(248, 'RAHMAD TAUFIK ZEEN', NOW(), NOW()),
(249, 'MIFTAHUL HUDA', NOW(), NOW()),
(250, 'M. BASORI', NOW(), NOW()),
(251, 'AHMAD MUSYANTO', NOW(), NOW()),
(252, 'SETYO NOEGROHO', NOW(), NOW()),
(253, 'DEDY MISWIDYANTO', NOW(), NOW()),
(254, 'ISMAIL', NOW(), NOW()),
(255, 'TARMUJI', NOW(), NOW()),
(256, 'NURHADI', NOW(), NOW()),
(257, 'SAPUAN', NOW(), NOW()),
(258, 'M. EKO NUR JAELANI', NOW(), NOW()),
(259, 'ABDULLAH USMAN FARUQI', NOW(), NOW()),
(260, 'MIRZA P', NOW(), NOW()),
(261, 'AS''AD SAMSUL', NOW(), NOW()),
(262, 'ABD MUJIB', NOW(), NOW()),
(263, 'SAMSUL ANAM', NOW(), NOW()),
(264, 'FASHIKIN', NOW(), NOW()),
(265, 'KHUSNAN', NOW(), NOW()),
(266, 'M hamdan', NOW(), NOW()),
(267, 'MAAD HAZBULLOH E', NOW(), NOW()),
(268, 'ARIS D W', NOW(), NOW()),
(269, 'SHOLIHAN', NOW(), NOW()),
(270, 'Ach. yunan u', NOW(), NOW()),
(271, 'A. JUNAEDI', NOW(), NOW()),
(272, 'MISBACHUL MUNIR', NOW(), NOW()),
(273, 'ROFIK', NOW(), NOW()),
(274, 'MASHUDI', NOW(), NOW()),
(275, 'A. RIFA''I', NOW(), NOW()),
(276, 'ADI GUNAWAN', NOW(), NOW()),
(277, 'JODI', NOW(), NOW()),
(278, 'MEI AGUNG', NOW(), NOW()),
(279, 'JAINUL H', NOW(), NOW()),
(280, 'CHOIRI', NOW(), NOW()),
(281, 'MUTHAROSIDI', NOW(), NOW()),
(282, 'JAMIN', NOW(), NOW()),
(283, 'M. SAMSUL ARIFIN', NOW(), NOW()),
(284, 'SHABIKIN', NOW(), NOW()),
(285, 'DENNY CAHYO', NOW(), NOW()),
(286, 'M. Abdul Ghoniy', NOW(), NOW()),
(287, 'AHMAD MURZAKI', NOW(), NOW()),
(288, 'KHOLIQIN', NOW(), NOW()),
(289, 'MUH ABDUL MAJID', NOW(), NOW()),
(290, 'KHOZIM', NOW(), NOW()),
(291, 'M. ISROQI', NOW(), NOW()),
(292, 'WARTONO', NOW(), NOW()),
(293, 'DANANG WAHYUDI', NOW(), NOW()),
(294, 'GILANG', NOW(), NOW()),
(295, 'KHAFID', NOW(), NOW()),
(296, 'M. SHOLEH', NOW(), NOW()),
(297, 'SUUDI', NOW(), NOW()),
(298, 'IHMALUL HUSAUNi', NOW(), NOW()),
(299, 'HANAFI', NOW(), NOW()),
(300, 'A. MUKLIS', NOW(), NOW()),
(301, 'AGUS DWI Y', NOW(), NOW()),
(302, 'SYAIFUL PRIO', NOW(), NOW()),
(303, 'BAHRUL ANAM', NOW(), NOW()),
(304, 'ABD. ASHAR MUKHLIS', NOW(), NOW()),
(305, 'GURUH', NOW(), NOW()),
(306, 'RIFAI', NOW(), NOW()),
(307, 'M NIDHOM', NOW(), NOW()),
(308, 'MIJO', NOW(), NOW());

INSERT INTO `unit_alats` (`id`, `unit_kerja_id`, `jenis_alat_id`, `no_lambung`, `kepemilikan`, `created_at`, `updated_at`) VALUES
(1, 1, 1, '57', 'PCS', NOW(), NOW()),
(2, 1, 1, '58', 'PCS', NOW(), NOW()),
(3, 1, 1, '59', 'PCS', NOW(), NOW()),
(4, 1, 1, '60', 'PCS', NOW(), NOW()),
(5, 2, 1, '61', 'PCS', NOW(), NOW()),
(6, 2, 1, '70', 'PCS', NOW(), NOW()),
(7, 2, 1, '25-12', 'PCS', NOW(), NOW()),
(8, 2, 1, '25-13', 'PCS', NOW(), NOW()),
(9, 2, 1, '25-14', 'PCS', NOW(), NOW()),
(10, 3, 1, '75', 'YAYASAN', NOW(), NOW()),
(11, 3, 1, '87', 'PCS', NOW(), NOW()),
(12, 3, 1, '88', 'PCS', NOW(), NOW()),
(13, 3, 1, '89', 'PCS', NOW(), NOW()),
(14, 3, 1, '25-90', 'YAYASAN', NOW(), NOW()),
(15, 3, 1, '25-91', 'YAYASAN', NOW(), NOW()),
(16, 3, 1, '25-92', 'YAYASAN', NOW(), NOW()),
(17, 3, 1, '25-93', 'YAYASAN', NOW(), NOW()),
(18, 4, 1, '74', 'PCS', NOW(), NOW()),
(19, 5, 1, '25-94', 'YAYASAN', NOW(), NOW()),
(20, 5, 1, '25-95', 'YAYASAN', NOW(), NOW()),
(21, 5, 1, '25-96', 'YAYASAN', NOW(), NOW()),
(22, 5, 1, '25-97', 'YAYASAN', NOW(), NOW()),
(23, 5, 1, '25-98', 'YAYASAN', NOW(), NOW()),
(24, 5, 1, '25-99', 'YAYASAN', NOW(), NOW()),
(25, 6, 1, '25-01', 'YAYASAN', NOW(), NOW()),
(26, 6, 1, '25-02', 'YAYASAN', NOW(), NOW()),
(27, 6, 1, '25-03', 'YAYASAN', NOW(), NOW()),
(28, 6, 1, '25-04', 'YAYASAN', NOW(), NOW()),
(29, 6, 1, '25-05', 'YAYASAN', NOW(), NOW()),
(30, 6, 1, '25-06', 'YAYASAN', NOW(), NOW()),
(31, 6, 1, '25-07', 'YAYASAN', NOW(), NOW()),
(32, 6, 1, '25-08', 'YAYASAN', NOW(), NOW()),
(33, 7, 1, '53', 'YAYASAN', NOW(), NOW()),
(34, 7, 1, '79', 'YAYASAN', NOW(), NOW()),
(35, 7, 1, '25-09', 'YAYASAN', NOW(), NOW()),
(36, 7, 1, '25-10', 'YAYASAN', NOW(), NOW()),
(37, 8, 1, '50', 'PCS', NOW(), NOW()),
(38, 8, 1, '77', 'YAYASAN', NOW(), NOW()),
(39, 9, 1, '78', 'PCS', NOW(), NOW()),
(40, 10, 1, '65', 'PCS', NOW(), NOW()),
(41, 11, 1, '64', 'PCS', NOW(), NOW()),
(42, 12, 1, '63', 'YAYASAN', NOW(), NOW()),
(43, 13, 1, '25-11', 'PCS', NOW(), NOW()),
(44, 13, 1, '62', 'PCS', NOW(), NOW()),
(45, 14, 1, '71', 'PCS', NOW(), NOW()),
(46, 14, 1, '72', 'PCS', NOW(), NOW()),
(47, 14, 1, '73', 'PCS', NOW(), NOW()),
(48, 14, 1, '80', 'PCS', NOW(), NOW()),
(49, 14, 1, '81', 'PCS', NOW(), NOW()),
(50, 15, 1, '67', 'PCS', NOW(), NOW()),
(51, 15, 1, '82', 'YAYASAN', NOW(), NOW()),
(52, 15, 1, '83', 'PCS', NOW(), NOW()),
(53, 15, 1, '84', 'PCS', NOW(), NOW()),
(54, 15, 1, '85', 'YAYASAN', NOW(), NOW()),
(55, 16, 1, '25-15', 'K3PG', NOW(), NOW()),
(56, 16, 1, '25-16', 'K3PG', NOW(), NOW()),
(57, 16, 1, '68', 'YAYASAN', NOW(), NOW()),
(58, 16, 1, '76', 'YAYASAN', NOW(), NOW()),
(59, 16, 1, '86', 'YAYASAN', NOW(), NOW()),
(60, 17, 2, '46', 'PCS', NOW(), NOW()),
(61, 18, 2, '60', 'WKK', NOW(), NOW()),
(62, 19, 2, '49', 'PCS', NOW(), NOW()),
(63, 20, 2, '25-71', 'PCS', NOW(), NOW()),
(64, 21, 2, '25-75', 'BAA', NOW(), NOW()),
(65, 22, 2, '67', 'PCS', NOW(), NOW()),
(66, 23, 2, '25-77', 'PCS', NOW(), NOW()),
(67, 23, 2, '43', 'PCS', NOW(), NOW()),
(68, 24, 2, '26-78', 'BAA', NOW(), NOW()),
(69, 24, 2, '65', 'PCS', NOW(), NOW()),
(70, 25, 2, '47', 'WKK', NOW(), NOW()),
(71, 26, 2, '41', 'WKK', NOW(), NOW()),
(72, 27, 2, '25-74', 'PCS', NOW(), NOW()),
(73, 28, 2, '45', 'PCS', NOW(), NOW()),
(74, 29, 2, '25-76', 'BAA', NOW(), NOW()),
(75, 29, 2, '50', 'BAA', NOW(), NOW()),
(76, 30, 2, '40', 'PCS', NOW(), NOW()),
(77, 31, 2, '25-72', 'PCS', NOW(), NOW()),
(78, 31, 2, '56', 'PCS', NOW(), NOW()),
(79, 32, 2, '25-73', 'PCS', NOW(), NOW()),
(80, 33, 2, '68', 'WKK', NOW(), NOW()),
(81, 34, 2, '55', 'WKK', NOW(), NOW()),
(82, 35, 2, '63', 'WKK', NOW(), NOW()),
(83, 36, 2, '64', 'PCS', NOW(), NOW()),
(84, 37, 2, '59', 'PCS', NOW(), NOW()),
(85, 37, 2, '54', 'PCS', NOW(), NOW()),
(86, 38, 2, '62', 'PCS', NOW(), NOW());

INSERT INTO `unit_operators` (`unit_alat_id`, `operator_id`, `grup`, `created_at`, `updated_at`) VALUES
(1, 1, 'A', NOW(), NOW()),
(2, 2, 'A', NOW(), NOW()),
(2, 3, 'B', NOW(), NOW()),
(2, 4, 'C', NOW(), NOW()),
(2, 5, 'D', NOW(), NOW()),
(3, 6, 'A', NOW(), NOW()),
(3, 7, 'B', NOW(), NOW()),
(3, 8, 'C', NOW(), NOW()),
(3, 9, 'D', NOW(), NOW()),
(4, 10, 'A', NOW(), NOW()),
(4, 11, 'B', NOW(), NOW()),
(4, 12, 'C', NOW(), NOW()),
(4, 13, 'D', NOW(), NOW()),
(5, 14, 'A', NOW(), NOW()),
(5, 15, 'B', NOW(), NOW()),
(5, 16, 'C', NOW(), NOW()),
(5, 17, 'D', NOW(), NOW()),
(6, 18, 'A', NOW(), NOW()),
(6, 19, 'B', NOW(), NOW()),
(6, 20, 'C', NOW(), NOW()),
(6, 21, 'D', NOW(), NOW()),
(7, 22, 'A', NOW(), NOW()),
(7, 23, 'B', NOW(), NOW()),
(7, 24, 'C', NOW(), NOW()),
(7, 25, 'D', NOW(), NOW()),
(8, 26, 'A', NOW(), NOW()),
(8, 27, 'B', NOW(), NOW()),
(8, 28, 'C', NOW(), NOW()),
(8, 29, 'D', NOW(), NOW()),
(9, 30, 'A', NOW(), NOW()),
(9, 31, 'B', NOW(), NOW()),
(9, 32, 'C', NOW(), NOW()),
(9, 33, 'D', NOW(), NOW()),
(10, 34, 'A', NOW(), NOW()),
(10, 35, 'B', NOW(), NOW()),
(10, 36, 'C', NOW(), NOW()),
(10, 37, 'D', NOW(), NOW()),
(11, 38, 'A', NOW(), NOW()),
(11, 39, 'B', NOW(), NOW()),
(11, 40, 'C', NOW(), NOW()),
(11, 41, 'D', NOW(), NOW()),
(12, 42, 'A', NOW(), NOW()),
(12, 43, 'B', NOW(), NOW()),
(12, 44, 'C', NOW(), NOW()),
(12, 45, 'D', NOW(), NOW()),
(13, 46, 'A', NOW(), NOW()),
(13, 47, 'B', NOW(), NOW()),
(13, 48, 'C', NOW(), NOW()),
(13, 49, 'D', NOW(), NOW()),
(14, 50, 'A', NOW(), NOW()),
(14, 51, 'B', NOW(), NOW()),
(14, 52, 'C', NOW(), NOW()),
(14, 53, 'D', NOW(), NOW()),
(15, 54, 'A', NOW(), NOW()),
(15, 55, 'B', NOW(), NOW()),
(15, 56, 'C', NOW(), NOW()),
(15, 57, 'D', NOW(), NOW()),
(16, 58, 'A', NOW(), NOW()),
(16, 59, 'B', NOW(), NOW()),
(16, 60, 'C', NOW(), NOW()),
(16, 61, 'D', NOW(), NOW()),
(17, 62, 'A', NOW(), NOW()),
(17, 63, 'B', NOW(), NOW()),
(17, 64, 'C', NOW(), NOW()),
(17, 65, 'D', NOW(), NOW()),
(18, 66, 'A', NOW(), NOW()),
(18, 67, 'B', NOW(), NOW()),
(18, 68, 'C', NOW(), NOW()),
(18, 69, 'D', NOW(), NOW()),
(19, 70, 'A', NOW(), NOW()),
(19, 71, 'B', NOW(), NOW()),
(19, 72, 'C', NOW(), NOW()),
(19, 73, 'D', NOW(), NOW()),
(20, 74, 'A', NOW(), NOW()),
(20, 75, 'B', NOW(), NOW()),
(20, 76, 'C', NOW(), NOW()),
(20, 77, 'D', NOW(), NOW()),
(21, 78, 'A', NOW(), NOW()),
(21, 79, 'B', NOW(), NOW()),
(21, 80, 'C', NOW(), NOW()),
(21, 81, 'D', NOW(), NOW()),
(22, 82, 'A', NOW(), NOW()),
(22, 83, 'B', NOW(), NOW()),
(22, 84, 'C', NOW(), NOW()),
(22, 85, 'D', NOW(), NOW()),
(23, 86, 'A', NOW(), NOW()),
(23, 87, 'B', NOW(), NOW()),
(23, 88, 'C', NOW(), NOW()),
(23, 89, 'D', NOW(), NOW()),
(24, 90, 'A', NOW(), NOW()),
(24, 91, 'B', NOW(), NOW()),
(24, 92, 'C', NOW(), NOW()),
(24, 93, 'D', NOW(), NOW()),
(25, 94, 'A', NOW(), NOW()),
(25, 95, 'B', NOW(), NOW()),
(25, 96, 'C', NOW(), NOW()),
(25, 97, 'D', NOW(), NOW()),
(26, 98, 'A', NOW(), NOW()),
(26, 99, 'B', NOW(), NOW()),
(26, 100, 'C', NOW(), NOW()),
(26, 101, 'D', NOW(), NOW()),
(27, 102, 'A', NOW(), NOW()),
(27, 103, 'B', NOW(), NOW()),
(27, 104, 'C', NOW(), NOW()),
(27, 105, 'D', NOW(), NOW()),
(28, 106, 'A', NOW(), NOW()),
(28, 107, 'B', NOW(), NOW()),
(28, 108, 'C', NOW(), NOW()),
(28, 109, 'D', NOW(), NOW()),
(29, 110, 'A', NOW(), NOW()),
(29, 111, 'B', NOW(), NOW()),
(29, 112, 'C', NOW(), NOW()),
(29, 113, 'D', NOW(), NOW()),
(30, 114, 'A', NOW(), NOW()),
(30, 115, 'B', NOW(), NOW()),
(30, 116, 'C', NOW(), NOW()),
(30, 117, 'D', NOW(), NOW()),
(31, 118, 'A', NOW(), NOW()),
(31, 119, 'B', NOW(), NOW()),
(31, 120, 'C', NOW(), NOW()),
(31, 121, 'D', NOW(), NOW()),
(32, 122, 'A', NOW(), NOW()),
(32, 123, 'B', NOW(), NOW()),
(32, 124, 'C', NOW(), NOW()),
(32, 125, 'D', NOW(), NOW()),
(33, 126, 'A', NOW(), NOW()),
(33, 127, 'B', NOW(), NOW()),
(33, 128, 'C', NOW(), NOW()),
(33, 129, 'D', NOW(), NOW()),
(34, 130, 'A', NOW(), NOW()),
(34, 131, 'B', NOW(), NOW()),
(34, 132, 'C', NOW(), NOW()),
(34, 133, 'D', NOW(), NOW()),
(35, 134, 'A', NOW(), NOW()),
(35, 135, 'B', NOW(), NOW()),
(35, 136, 'C', NOW(), NOW()),
(35, 137, 'D', NOW(), NOW()),
(36, 138, 'A', NOW(), NOW()),
(36, 139, 'B', NOW(), NOW()),
(36, 140, 'C', NOW(), NOW()),
(36, 141, 'D', NOW(), NOW()),
(37, 142, 'A', NOW(), NOW()),
(38, 143, 'A', NOW(), NOW()),
(38, 144, 'B', NOW(), NOW()),
(38, 145, 'C', NOW(), NOW()),
(38, 146, 'D', NOW(), NOW()),
(39, 147, 'A', NOW(), NOW()),
(39, 135, 'B', NOW(), NOW()),
(39, 148, 'C', NOW(), NOW()),
(39, 149, 'D', NOW(), NOW()),
(40, 150, 'A', NOW(), NOW()),
(40, 151, 'B', NOW(), NOW()),
(40, 71, 'C', NOW(), NOW()),
(40, 152, 'D', NOW(), NOW()),
(41, 153, 'A', NOW(), NOW()),
(41, 154, 'B', NOW(), NOW()),
(41, 155, 'C', NOW(), NOW()),
(41, 156, 'D', NOW(), NOW()),
(42, 157, 'A', NOW(), NOW()),
(42, 158, 'B', NOW(), NOW()),
(42, 159, 'C', NOW(), NOW()),
(42, 160, 'D', NOW(), NOW()),
(43, 161, 'A', NOW(), NOW()),
(44, 162, 'A', NOW(), NOW()),
(45, 163, 'A', NOW(), NOW()),
(45, 164, 'B', NOW(), NOW()),
(45, 165, 'C', NOW(), NOW()),
(45, 18, 'D', NOW(), NOW()),
(46, 166, 'A', NOW(), NOW()),
(46, 167, 'B', NOW(), NOW()),
(46, 168, 'C', NOW(), NOW()),
(46, 169, 'D', NOW(), NOW()),
(47, 170, 'A', NOW(), NOW()),
(47, 18, 'B', NOW(), NOW()),
(47, 171, 'C', NOW(), NOW()),
(47, 172, 'D', NOW(), NOW()),
(48, 173, 'A', NOW(), NOW()),
(48, 174, 'B', NOW(), NOW()),
(48, 175, 'C', NOW(), NOW()),
(48, 176, 'D', NOW(), NOW()),
(49, 177, 'A', NOW(), NOW()),
(49, 178, 'B', NOW(), NOW()),
(49, 179, 'C', NOW(), NOW()),
(49, 180, 'D', NOW(), NOW()),
(50, 151, 'A', NOW(), NOW()),
(50, 181, 'B', NOW(), NOW()),
(50, 182, 'C', NOW(), NOW()),
(50, 183, 'D', NOW(), NOW()),
(51, 184, 'A', NOW(), NOW()),
(51, 185, 'B', NOW(), NOW()),
(51, 186, 'C', NOW(), NOW()),
(51, 187, 'D', NOW(), NOW()),
(52, 151, 'A', NOW(), NOW()),
(52, 181, 'B', NOW(), NOW()),
(52, 188, 'C', NOW(), NOW()),
(52, 189, 'D', NOW(), NOW()),
(53, 190, 'A', NOW(), NOW()),
(53, 191, 'B', NOW(), NOW()),
(53, 192, 'C', NOW(), NOW()),
(53, 193, 'D', NOW(), NOW());

INSERT INTO `unit_operators` (`unit_alat_id`, `operator_id`, `grup`, `created_at`, `updated_at`) VALUES
(54, 194, 'A', NOW(), NOW()),
(54, 195, 'B', NOW(), NOW()),
(54, 196, 'C', NOW(), NOW()),
(54, 80, 'D', NOW(), NOW()),
(55, 197, 'A', NOW(), NOW()),
(55, 198, 'B', NOW(), NOW()),
(55, 199, 'C', NOW(), NOW()),
(55, 200, 'D', NOW(), NOW()),
(56, 201, 'A', NOW(), NOW()),
(56, 185, 'B', NOW(), NOW()),
(56, 199, 'C', NOW(), NOW()),
(56, 202, 'D', NOW(), NOW()),
(57, 203, 'A', NOW(), NOW()),
(57, 204, 'B', NOW(), NOW()),
(57, 205, 'C', NOW(), NOW()),
(57, 187, 'D', NOW(), NOW()),
(58, 197, 'A', NOW(), NOW()),
(58, 206, 'B', NOW(), NOW()),
(58, 186, 'C', NOW(), NOW()),
(58, 207, 'D', NOW(), NOW()),
(59, 208, 'A', NOW(), NOW()),
(59, 198, 'B', NOW(), NOW()),
(59, 182, 'C', NOW(), NOW()),
(59, 183, 'D', NOW(), NOW()),
(60, 209, 'A', NOW(), NOW()),
(60, 210, 'B', NOW(), NOW()),
(60, 211, 'C', NOW(), NOW()),
(60, 212, 'D', NOW(), NOW()),
(61, 213, 'A', NOW(), NOW()),
(61, 214, 'B', NOW(), NOW()),
(61, 215, 'C', NOW(), NOW()),
(61, 216, 'D', NOW(), NOW()),
(62, 217, 'A', NOW(), NOW()),
(62, 218, 'B', NOW(), NOW()),
(62, 219, 'C', NOW(), NOW()),
(62, 220, 'D', NOW(), NOW()),
(63, 221, 'A', NOW(), NOW()),
(63, 222, 'B', NOW(), NOW()),
(63, 223, 'C', NOW(), NOW()),
(63, 224, 'D', NOW(), NOW()),
(64, 225, 'A', NOW(), NOW()),
(64, 226, 'B', NOW(), NOW()),
(64, 227, 'C', NOW(), NOW()),
(64, 228, 'D', NOW(), NOW()),
(65, 229, 'A', NOW(), NOW()),
(65, 230, 'B', NOW(), NOW()),
(65, 231, 'C', NOW(), NOW()),
(65, 232, 'D', NOW(), NOW()),
(66, 233, 'A', NOW(), NOW()),
(66, 234, 'B', NOW(), NOW()),
(66, 215, 'C', NOW(), NOW()),
(66, 235, 'D', NOW(), NOW()),
(67, 236, 'A', NOW(), NOW()),
(67, 237, 'B', NOW(), NOW()),
(67, 227, 'C', NOW(), NOW()),
(67, 26, 'D', NOW(), NOW()),
(68, 238, 'A', NOW(), NOW()),
(68, 239, 'B', NOW(), NOW()),
(68, 240, 'C', NOW(), NOW()),
(68, 241, 'D', NOW(), NOW()),
(69, 242, 'A', NOW(), NOW()),
(69, 243, 'B', NOW(), NOW()),
(69, 244, 'C', NOW(), NOW()),
(69, 245, 'D', NOW(), NOW()),
(70, 246, 'A', NOW(), NOW()),
(70, 247, 'B', NOW(), NOW()),
(70, 248, 'C', NOW(), NOW()),
(70, 249, 'D', NOW(), NOW()),
(71, 250, 'A', NOW(), NOW()),
(71, 251, 'B', NOW(), NOW()),
(71, 252, 'C', NOW(), NOW()),
(71, 253, 'D', NOW(), NOW()),
(72, 254, 'A', NOW(), NOW()),
(72, 255, 'B', NOW(), NOW()),
(72, 256, 'C', NOW(), NOW()),
(72, 257, 'D', NOW(), NOW()),
(73, 258, 'A', NOW(), NOW()),
(73, 259, 'B', NOW(), NOW()),
(73, 256, 'C', NOW(), NOW()),
(73, 257, 'D', NOW(), NOW()),
(74, 260, 'A', NOW(), NOW()),
(74, 261, 'B', NOW(), NOW()),
(74, 262, 'C', NOW(), NOW()),
(74, 263, 'D', NOW(), NOW()),
(75, 264, 'A', NOW(), NOW()),
(75, 265, 'B', NOW(), NOW()),
(75, 266, 'C', NOW(), NOW()),
(75, 267, 'D', NOW(), NOW()),
(76, 268, 'A', NOW(), NOW()),
(76, 269, 'B', NOW(), NOW()),
(76, 270, 'C', NOW(), NOW()),
(76, 271, 'D', NOW(), NOW()),
(77, 272, 'A', NOW(), NOW()),
(77, 273, 'B', NOW(), NOW()),
(77, 274, 'C', NOW(), NOW()),
(77, 275, 'D', NOW(), NOW()),
(78, 276, 'A', NOW(), NOW()),
(78, 277, 'B', NOW(), NOW()),
(78, 278, 'C', NOW(), NOW()),
(78, 156, 'D', NOW(), NOW()),
(79, 279, 'A', NOW(), NOW()),
(79, 280, 'B', NOW(), NOW()),
(79, 281, 'C', NOW(), NOW()),
(79, 282, 'D', NOW(), NOW()),
(80, 179, 'A', NOW(), NOW()),
(80, 283, 'B', NOW(), NOW()),
(80, 284, 'C', NOW(), NOW()),
(80, 285, 'D', NOW(), NOW()),
(81, 286, 'A', NOW(), NOW()),
(81, 287, 'B', NOW(), NOW()),
(81, 288, 'C', NOW(), NOW()),
(81, 289, 'D', NOW(), NOW()),
(82, 290, 'A', NOW(), NOW()),
(82, 291, 'B', NOW(), NOW()),
(82, 292, 'C', NOW(), NOW()),
(82, 293, 'D', NOW(), NOW()),
(83, 294, 'A', NOW(), NOW()),
(83, 18, 'B', NOW(), NOW()),
(83, 295, 'C', NOW(), NOW()),
(83, 296, 'D', NOW(), NOW()),
(84, 297, 'A', NOW(), NOW()),
(84, 298, 'B', NOW(), NOW()),
(84, 299, 'C', NOW(), NOW()),
(84, 300, 'D', NOW(), NOW()),
(85, 301, 'A', NOW(), NOW()),
(85, 302, 'B', NOW(), NOW()),
(85, 303, 'C', NOW(), NOW()),
(85, 304, 'D', NOW(), NOW()),
(86, 305, 'A', NOW(), NOW()),
(86, 306, 'B', NOW(), NOW()),
(86, 307, 'C', NOW(), NOW()),
(86, 308, 'D', NOW(), NOW());

-- ---------------------------------------------------------------------
-- Data master: Pengawas (dari tabel Daftar Pengawas di Excel)
-- ---------------------------------------------------------------------
INSERT INTO `pengawas` (`nama`, `wilayah`, `created_at`, `updated_at`) VALUES
('Iin', 'I A', NOW(), NOW()),
('Agus', 'I A', NOW(), NOW()),
('Lugito', 'I A', NOW(), NOW()),
('Yudha', 'I A', NOW(), NOW()),
('Mat Yakin', 'I B', NOW(), NOW()),
('Suyono Sby', 'I B', NOW(), NOW()),
('Toha', 'I B', NOW(), NOW()),
('Nairi', 'I B', NOW(), NOW()),
('Janjang', 'II A', NOW(), NOW()),
('Fatchur', 'II A', NOW(), NOW()),
('Sumardiono', 'II A', NOW(), NOW()),
('Suyono La', 'II A', NOW(), NOW()),
('Aziz', 'II B', NOW(), NOW()),
('Dwi Yasse', 'II B', NOW(), NOW()),
('Fauzi', 'II B', NOW(), NOW()),
('Aries', 'II B', NOW(), NOW()),
('Masrur', 'III', NOW(), NOW()),
('Junaidi', 'III', NOW(), NOW()),
('Rudy', 'III', NOW(), NOW()),
('Machrus', 'III', NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;

-- SELESAI. Total data: 6 zona, 13 area kerja, 38 unit kerja, 2 jenis alat,
-- 308 operator, 86 unit alat, 332 penugasan operator grup, 20 pengawas.